### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [DasOakster/pg-wodehouse_indiscretions-of-archie#1]
**Dedication:**
- [x] The dedication title should appear in the ToC. It should be formatted like:
`<h2 epub:type="title">Dedication to <abbr epub:type="z3998:given-name">B. W.</abbr> King-Hall</h2>`

- [x] The dedication is a letter and should be formatted as such. See [SEMOS 7.7](https://standardebooks.org/manual/1.6.2/7-high-level-structural-patterns#7.7). All of the text should be inside of a `<blockquote epub:type="z3998:letter">`, and you no longer need the `<div class="body">`s.

- You can keep the label "To My Best Friend X" in its own `<blockquote>`.

- [x] According to your page scans, the label should look like:
```
			<blockquote>
				<p>To<br/>
				My Best Friend<br/>
				x</p>
			</blockquote>
```

- [x]  "X" in the label needs to be capitalized.

- [x] Make sure to move "Yours ever," into the `<footer>`.

- [x] The paragraph beginning with "than X cuts you in Piccadilly..." needs a `class="continued"` on the `<p>` ([SEMOS 8.4.2.1](https://standardebooks.org/manual/1.6.2/single-page#8.4.2.1)).

**Chapter 2:**
- [x] Carte blanche appears in Merriam-Webster and doesn't need to be italicized ([SEMOS 8.2.9.1](https://standardebooks.org/manual/1.6.2/single-page#8.2.9.1)).

**Chapter 3:**
- [x] Née appears in Merriam-Webster and doesn't need to be italicized.

**Chapter 12:**
- [x] Rapprochement appears in Merriam-Webster and doesn't need to be italicized.

- [x] Camaraderie appears in Merriam-Webster and doesn't need to be italicized.

**Chapter 13:**
- [x] Negligee appears in Merriam-Webster and doesn't need to be italicized.

**Chapter 18:**
- [x] De trop appears in Merriam-Webster and doesn't need to be italicized.

**Chapter 19:**
- [x] The headline and the article should be contained in one `<blockquote>`.

- [x] We want to avoid using custom classes that are used once or twice. Remove `class="headline"`.

- [x] The whole headline can be inside the `<header>`.

- [x] For consistency, make "Revelry by Night." its own paragraph.

- [x] Remove `epub:type="z3998:article"`. This semantic is only applied to major sectioning elements.

**Chapter 21:**
- [x] Tête-à-tête appears in Merriam-Webster and doesn't need to be italicized.

- [x] Remove `class="headline"`.

- [x] A better way of formatting the poster is:
```
			<blockquote>
				<header>
					<p>Clover Leaf Social and Outing Club<br/>
					Grand Contest<br/>
					Pie-Eating Championship of the West Side</p>
				</header>
				<p><b>Spike O’Dowd</b><br/>
				(Champion)<br/>
				<abbr>v.</abbr><br/>
				<b>Blake’s Unknown</b><br/>
				<b>For a Purse of $50 and Side-Bet</b></p>
			</blockquote>
```
This makes it easier to style with minimal CSS.

**Chapter 22:**
- [x] Remove `class="headline"` and `epub:type="z3998:article"`.

- [x] Née appears in Merriam-Webster and doesn't need to be italicized.

**Chapter 23:**
- [x] For poem/ song indentation, the indentation number is changed rather than the incrementing amount of padding. Your song indentation in Chapter 23 should be:
class="i1" --> class="i2"
class="i2" --> class="i4"
class="i3" --> class="i14"
The corresponding CSS is listed below.

**Chapter 26:**
- [x] Remove "THE END".

**local.css:**
- [x] You are missing letter CSS ([SEMOS 7.7](https://standardebooks.org/manual/1.6.2/7-high-level-structural-patterns#7.7)).

- [x] For the dedication, you can replace:
```
#dedication header{
	text-align: center;
	font-size: 1.2em;
	font-variant: small-caps;
}

#dedication blockquote{
	text-align: center;
	font-variant: all-small-caps;
	margin: 10px;
}

#dedication footer{
	padding-left: 11em;
	font-variant: small-caps;
}

div.body{
	text-align: initial;
	font-style: italic;
}
```
with:
```
#dedication blockquote > blockquote{
	text-align: center;
	font-variant: all-small-caps;
}
```

- [x] For Chapters 19, 21, and 22, you can replace:
```
.headline{
	font-variant: small-caps;
	text-align: center;
}
```
with:
```
#chapter-19 blockquote > header,
#chapter-21 blockquote > header{
	font-variant: small-caps;
	padding-bottom: 1em;
	text-align: center;
}

#chapter-21 blockquote{
	text-align: center;
}

#chapter-22 blockquote:first-of-type{
	font-variant: small-caps;
	text-align: center;
}
```

- [x] Remove the duplicate poem CSS.

- [x] Since the poem and song CSS uses the same styling, we can combine the selectors like this:
```
[epub|type~="z3998:poem"] p,
[epub|type~="z3998:song"] p{
	text-align: initial;
	text-indent: 0;
}

[epub|type~="z3998:poem"] p > span,
[epub|type~="z3998:song"] p > span{
	display: block;
	padding-left: 1em;
	text-indent: -1em;
}

[epub|type~="z3998:poem"] p > span + br,
[epub|type~="z3998:song"] p > span + br{
	display: none;
}
```

- [x] Your song indentation CSS for Chapter 23 should actually be:
```
p span.i2{
	padding-left: 3em;
	text-indent: -1em;
}

p span.i4{
	padding-left: 5em;
	text-indent: -1em;
}

p span.i14{
	padding-left: 15em;
	text-indent: -1em;
}
```

**content.opf:**
- [x] In your long description, convert the single quotes in to double quotes.

**Misc.:**
- [x] Run `se clean .` and commit the changes.

- [x] Run `se typogrify .` and commit the changes.

- [x] `se modernize-spelling .` wants to make some changes. Make sure these are correct and commit them.

- [x] Run `se build-title .` and commit the changes.

- [x] Run `se build-toc .` and commit the changes.

- After all of the changes have been made run `se clean .` and `se lint .` to make sure nothing changes and there are no more errors.

**Comment by EmmaSweeney** [comment]
Dedication:
- [x] You need to add `<p epub:type="z3998:salutation">` to "My dear Buddy⁠—".

- [x] You need to add `<p epub:type="z3998:valediction">` to "Yours ever".

Chapter 7:
- [x] Rami appears in Merriam-Webster and doesn't need to be italicized.

local.css:
- [x] To fix the text alignment and margins issues in the dedication add this CSS. Place it with the other custom CSS for easy finding.
```
#dedication blockquote[epub|type~="z3998:letter"]{
	margin: 1em 0;
	text-align: initial;
}
```

content.opf:

- [x] You are missing the LoC Names Database page for the cover artist ([http://id.loc.gov/authorities/names/nr93045191](http://id.loc.gov/authorities/names/nr93045191)).
